#!/usr/bin/perl

foreach my $s (<STDIN>)
{
    if ($s =~ m|^\@include \"(.*)\"|)
    {
	my $file = $1;
	open(IN, "< $file") || die("couldn't open file $file");
	my @tab = <IN>;
	print @tab;
	close(IN);
	next;
    }
    print $s;
}
