#!/usr/bin/perl
# inline images references in the css:
# encode images in url('imgurl') and replace with data: urls.
# also set width and height if a /*img_size*/ comment is found.

foreach my $s (<STDIN>)
{
    if ($s =~ m|url\('(\.\./.*)'\)|)
    {
	my $file = $1;
	# print "found $file\n";

	# base64 encoding
	my $encoded = `base64 -w 0 $file`;
	$s =~ s|url\('[^']*'\)|url(\'data:image/png;base64,$encoded\')|;

	# width and height
	my $g = `file $file`;
	$g =~ m|([0-9]+) x ([0-9]+)|;
	my ($width, $height) = ($1, $2);
	#print "size: $width, $height\n";
	$s =~ s|/\* *img_size *\*/|width:${width}px; height:${height}px;|;

    }
    print $s;
}
