#!/usr/bin/perl
$xml=$ARGV[0];
open(IN, "< $xml") || die("pack_widgets: couldn't open file $xml");
my @lines = <IN>;

sub format_html_blob
{
    my ($s) = @_;
    # remove newlines.
    $s =~ s|\n||mg;
    # squish leading/trailing spaces
    $s =~ s|^[ \n\t]*||;
    $s =~ s|[ \n\t]*$||;
    # squish space between tags
    $s =~ s|>[ \n\t]*<|><|g;
    # squish even more spaces =P
    $s =~ s|>[ \n\t]*|>|g;
    $s =~ s|[ \n\t]*<|<|g;
    return $s;
}

my $id = "";
my $args = "";
my @current_widget;

sub dump_widget_layout
{
    print "      layout: '";
    print format_html_blob(join('', @current_widget));
    print "'";
}

sub dump_widget_init_proxy
{
    my ($id, $args_str) = (@_);
    my @args = split(" ", $args_str);
    @args = grep(!/init/, @args);

    if (@args == 0)
    {	return;   }
    print "      init_proxy: ";
    print "function(w, ph){ ${id}_init(w";
    foreach my $arg (@args)
    {  print ", ph.$arg";  }
    print "); },\n";
}

sub dump_widget_init
{
    my ($id, $args_str) = (@_);
    my @args = split(" ", $args_str);
    @args = grep(/init/, @args);
    
    if (@args == 0)
    {	return;   }
    print "      init: ${id}_init,\n";
}

sub dump_widget
{
    my ($last) = @_;
    return if ($id eq "");
    print "   '$id' : {\n";
    dump_widget_init($id, $args);
    dump_widget_init_proxy($id, $args);
    dump_widget_layout();
    print " }";
    print "," if ($last eq "");
    print "\n";

    @current_widget = ();
    $id = "";
}

sub dump_widgets
{
    foreach my $s (@lines)
    {
	# remove comments
	$s =~ s|<!--[^>]*-->||g;

	if ($s =~ m|<widget name="([^"]*)"([^>]*)>|)
	{
	    my ($new_id, $new_args) = ($1, $2);
	    dump_widget("");		# dump previous widget
	    ($id, $args) = ($new_id, $new_args);
	}
	elsif ($s =~ m|<widget .*>|) # sanity check
	{  die($s . "\nlooks like name=\"widget name\" attribute is missing"); }

	if ($s =~ m|<widgets *>|   ||
	    $s =~ m|</widgets *>|  )
	{ next; }

	if ($id ne "")
	{  push(@current_widget, $s); }
    }
    dump_widget("last");
}

print("    /* widgets (generated from $xml). */\n");
print("    var widgets = {\n");
dump_widgets();
print("    };\n\n");


sub widget_new_functions
{
    foreach my $s (@lines)
    {
	# remove comments
	$s =~ s|<!--[^>]*-->||g;

	if ($s =~ m|<widget name="([^"]*)"([^>]*)>|)
	{
	    my ($id, $args_str) = ($1, $2);
	    my @args = split(" ", $args_str);
	    @args = grep(!/init/, @args);

	    if (@args == 0)
	    {
		next; # these are rather useless
		print "    function new_$id()\n";
		print "    {\n";
		print "        return new_widget(\"$id\");\n";
		print "    }\n\n";
	    }
	    print "    function new_$id(" . join(", ", @args) . ")\n";
	    print "    {\n";
	    print "      return new_widget(\"$id\", function(w)\n";
	    print "        { ${id}_init(w";
	    foreach my $arg (@args)
	    {  print ", $arg";  }
	    print "); });\n";
	    print "    }\n\n";
	}
    }
}

print("    /* functions for creating widgets */\n");
widget_new_functions();
